In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("train (2).csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   text            5099 non-null   str
 1   ats_score       5099 non-null   float64
 2   original_label  5099 non-null   str
dtypes: float64(1), str(2)
memory usage: 41.4 MB

In [4]:
df.head(5)

                                                text  ats_score original_label
0  SummaryI am seeking a position wherein I may u...       80.6       Good Fit
1  ProfileHighly motivated Sales Associate with e...       24.3         No Fit
2  SummaryHaving achieved a milestone of 7 years ...       53.9  Potential Fit
3  SummaryWireless communications engineer with e...       52.5  Potential Fit
4  SummaryData Entry experienced and adept at inp...       59.2  Potential Fit

In [5]:

df=df.drop(columns=["original_label"])

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       5099 non-null   str
 1   ats_score  5099 non-null   float64
dtypes: float64(1), str(1)
memory usage: 41.3 MB

In [7]:
df["text"].isnull().value_counts()

text
False    5099
Name: count, dtype: int64

In [8]:
df["ats_score"].isnull().value_counts()

ats_score
False    5099
Name: count, dtype: int64

In [9]:
df["text"].duplicated().value_counts()

text
False    5099
Name: count, dtype: int64

In [10]:
df['text'].str.contains(r'\bSEP\b').value_counts()

text
True    5099
Name: count, dtype: int64

In [11]:
df[['resume_text', 'job_description']] = (
    df['text'].str.split('SEP', n=1, expand=True)
)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             5099 non-null   str
 1   ats_score        5099 non-null   float64
 2   resume_text      5099 non-null   str
 3   job_description  5099 non-null   str
dtypes: float64(1), str(3)
memory usage: 82.6 MB

In [13]:
df["resume_text"]=df["resume_text"].str.split()

In [14]:
df["job_description"]=df["job_description"].str.split()

In [15]:
df[['resume_text', 'job_description']].head()

,resume_text,job_description
0,"[SummaryI, am, seeking, a, position, wherein, ...","[-, Share, resume, to, shan, imrsoft.com, Job,..."
1,"[ProfileHighly, motivated, Sales, Associate, w...","[Purpose, StatementThe, Software, Engineering,..."
2,"[SummaryHaving, achieved, a, milestone, of, 7,...","[Title, Business, AnalystLocation, Santa, Clar..."
3,"[SummaryWireless, communications, engineer, wi...","[Job, Description, As, a, Principal, Software,..."
4,"[SummaryData, Entry, experienced, and, adept, ...","[Title, Data, EngineerLocation, fully, remote,..."

In [16]:
df['resume_text'] = df['resume_text'].apply(' '.join)
df['job_description'] = df['job_description'].apply(' '.join)

In [17]:
df[['resume_text', 'job_description']].head()

,resume_text,job_description
0,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title J...
1,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Mana...
2,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, CA..."
3,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engine...
4,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, howe..."

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             5099 non-null   str
 1   ats_score        5099 non-null   float64
 2   resume_text      5099 non-null   str
 3   job_description  5099 non-null   str
dtypes: float64(1), str(3)
memory usage: 82.6 MB

In [19]:
df=df.drop(columns=["text"])

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   resume_text      5099 non-null   str
 2   job_description  5099 non-null   str
dtypes: float64(1), str(2)
memory usage: 41.3 MB

In [21]:
df.to_csv("final_train_dataset.csv", index=False)

### validation dataset

In [32]:
val_df=pd.read_csv("validation.csv")

In [33]:
val_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   text            1275 non-null   str
 1   ats_score       1275 non-null   float64
 2   original_label  1275 non-null   str
dtypes: float64(1), str(2)
memory usage: 10.2 MB

In [34]:
val_df[['resume_text', 'job_description']] = (
    val_df['text'].str.split('SEP', n=1, expand=True)
)

In [35]:
val_df.head(5)

,text,ats_score,original_label,resume_text,job_description
0,SummaryFinancial Accountant specializing in fi...,27.6,No Fit,SummaryFinancial Accountant specializing in fi...,Role - Business Analyst - Mobile Location - ...
1,SummaryExperienced Data Analyst who responds t...,57.6,Potential Fit,SummaryExperienced Data Analyst who responds t...,( Candidates without any Visa Constraints) (...
2,SummaryDigital marketing professional experien...,22.4,No Fit,SummaryDigital marketing professional experien...,Brief Description Who is Monarch Tractor? At...
3,Professional SummaryHighly motivated Sales Ass...,28.0,No Fit,Professional SummaryHighly motivated Sales Ass...,About Hallgate Management Hallgate Managemen...
4,Professional SummaryCurrently working with Cat...,58.3,Potential Fit,Professional SummaryCurrently working with Cat...,"Pay Range 81k - 102k, depending on experienc..."

In [36]:
val_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   text             1275 non-null   str
 1   ats_score        1275 non-null   float64
 2   original_label   1275 non-null   str
 3   resume_text      1275 non-null   str
 4   job_description  1275 non-null   str
dtypes: float64(1), str(4)
memory usage: 20.4 MB

In [37]:
val_df=val_df.drop(columns=["original_label","text"])

In [38]:
val_df.head()

,ats_score,resume_text,job_description
0,27.6,SummaryFinancial Accountant specializing in fi...,Role - Business Analyst - Mobile Location - ...
1,57.6,SummaryExperienced Data Analyst who responds t...,( Candidates without any Visa Constraints) (...
2,22.4,SummaryDigital marketing professional experien...,Brief Description Who is Monarch Tractor? At...
3,28.0,Professional SummaryHighly motivated Sales Ass...,About Hallgate Management Hallgate Managemen...
4,58.3,Professional SummaryCurrently working with Cat...,"Pay Range 81k - 102k, depending on experienc..."

In [39]:
val_df.to_csv("final_validation_dataset.csv", index=False)